//
//  LWWallet.h
//
//  Created by Aaron Voisine on 9/1/15.
//  Copyright (c) 2015 breadwallet LLC
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

#ifndef LWWallet_h
#define LWWallet_h

#include "LWTransaction.h"
#include "LWAddress.h"
#include "LWBIP32Sequence.h"
#include "LWInt.h"
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DEFAULT_FEE_PER_KB ((5000ULL*1000 + 99)/100) // bitcoind 0.11 min relay fee on 100bytes
#define MIN_FEE_PER_KB     ((TX_FEE_PER_KB*1000 + 190)/191) // minimum relay fee on a 191byte tx
#define MAX_FEE_PER_KB     ((1000100ULL*1000 + 190)/191) // slightly higher than a 10000bit fee on a 191byte tx

typedef struct {
    UInt256 hash;
    uint32_t n;
} LWUTXO;

inline static size_t LWUTXOHash(const void *utxo)
{
    // (hash xor n)*FNV_PRIME
    return (size_t)((((const LWUTXO *)utxo)->hash.u32[0] ^ ((const LWUTXO *)utxo)->n)*0x01000193);
}

inline static int LWUTXOEq(const void *utxo, const void *otherUtxo)
{
    return (utxo == otherUtxo || (UInt256Eq(((const LWUTXO *)utxo)->hash, ((const LWUTXO *)otherUtxo)->hash) &&
                                  ((const LWUTXO *)utxo)->n == ((const LWUTXO *)otherUtxo)->n));
}

typedef struct LWWalletStruct LWWallet;

// allocates and populates a LWWallet struct that must be freed by calling LWWalletFree()
LWWallet *LWWalletNew(LWTransaction *transactions[], size_t txCount, LWMasterPubKey mpk);

// not thread-safe, set callbacks once after LWWalletNew(), before calling other LWWallet functions
// info is a void pointer that will be passed along with each callback call
// void balanceChanged(void *, uint64_t) - called when the wallet balance changes
// void txAdded(void *, LWTransaction *) - called when transaction is added to the wallet
// void txUpdated(void *, const UInt256[], size_t, uint32_t, uint32_t)
//   - called when the blockHeight or timestamp of previously added transactions are updated
// void txDeleted(void *, UInt256, int, int) - called when a previously added transaction is removed from the wallet
void LWWalletSetCallbacks(LWWallet *wallet, void *info,
                          void (*balanceChanged)(void *info, uint64_t balance),
                          void (*txAdded)(void *info, LWTransaction *tx),
                          void (*txUpdated)(void *info, const UInt256 txHashes[], size_t txCount, uint32_t blockHeight,
                                            uint32_t timestamp),
                          void (*txDeleted)(void *info, UInt256 txHash, int notifyUser, int recommendRescan));

// wallets are composed of chains of addresses
// each chain is traversed until a gap of a number of addresses is found that haven't been used in any transactions
// this function writes to addrs an array of <gapLimit> unused addresses following the last used address in the chain
// the internal chain is used for change addresses and the external chain for receive addresses
// addrs may be NULL to only generate addresses for LWWalletContainsAddress()
// returns the number addresses written to addrs
size_t LWWalletUnusedAddrs(LWWallet *wallet, LWAddress addrs[], uint32_t gapLimit, int internal);

// returns the first unused external address
LWAddress LWWalletReceiveAddress(LWWallet *wallet);

// writes all addresses previously genereated with LWWalletUnusedAddrs() to addrs
// returns the number addresses written, or total number available if addrs is NULL
size_t LWWalletAllAddrs(LWWallet *wallet, LWAddress addrs[], size_t addrsCount);

// true if the address was previously generated by LWWalletUnusedAddrs() (even if it's now used)
int LWWalletContainsAddress(LWWallet *wallet, const char *addr);

// true if the address was previously used as an input or output in any wallet transaction
int LWWalletAddressIsUsed(LWWallet *wallet, const char *addr);

// writes transactions registered in the wallet, sorted by date, oldest first, to the given transactions array
// returns the number of transactions written, or total number available if transactions is NULL
size_t LWWalletTransactions(LWWallet *wallet, LWTransaction *transactions[], size_t txCount);

// writes transactions registered in the wallet, and that were unconfirmed before blockHeight, to the transactions array
// returns the number of transactions written, or total number available if transactions is NULL
size_t LWWalletTxUnconfirmedBefore(LWWallet *wallet, LWTransaction *transactions[], size_t txCount,
                                   uint32_t blockHeight);

// current wallet balance, not including transactions known to be invalid
uint64_t LWWalletBalance(LWWallet *wallet);

// total amount spent from the wallet (exluding change)
uint64_t LWWalletTotalSent(LWWallet *wallet);

// total amount received by the wallet (exluding change)
uint64_t LWWalletTotalReceived(LWWallet *wallet);

// writes unspent outputs to utxos and returns the number of outputs written, or number available if utxos is NULL
size_t LWWalletUTXOs(LWWallet *wallet, LWUTXO utxos[], size_t utxosCount);

// fee-per-kb of transaction size to use when creating a transaction
uint64_t LWWalletFeePerKb(LWWallet *wallet);
void LWWalletSetFeePerKb(LWWallet *wallet, uint64_t feePerKb);

// returns an unsigned transaction that sends the specified amount from the wallet to the given address
// result must be freed using LWTransactionFree()
LWTransaction *LWWalletCreateTransaction(LWWallet *wallet, uint64_t amount, const char *addr);

// returns an unsigned transaction that satisifes the given transaction outputs
// result must be freed using LWTransactionFree()
LWTransaction *LWWalletCreateTxForOutputs(LWWallet *wallet, const LWTxOutput outputs[], size_t outCount);

// signs any inputs in tx that can be signed using private keys from the wallet
// forkId is 0 for bitcoin, 0x40 for b-cash
// seed is the master private key (wallet seed) corresponding to the master public key given when the wallet was created
// returns true if all inputs were signed, or false if there was an error or not all inputs were able to be signed
int LWWalletSignTransaction(LWWallet *wallet, LWTransaction *tx, int forkId, const void *seed, size_t seedLen);

// true if the given transaction is associated with the wallet (even if it hasn't been registered)
int LWWalletContainsTransaction(LWWallet *wallet, const LWTransaction *tx);

// adds a transaction to the wallet, or returns false if it isn't associated with the wallet
int LWWalletRegisterTransaction(LWWallet *wallet, LWTransaction *tx);

// removes a tx from the wallet and calls LWTransactionFree() on it, along with any tx that depend on its outputs
void LWWalletRemoveTransaction(LWWallet *wallet, UInt256 txHash);

// returns the transaction with the given hash if it's been registered in the wallet
LWTransaction *LWWalletTransactionForHash(LWWallet *wallet, UInt256 txHash);

// true if no previous wallet transaction spends any of the given transaction's inputs, and no inputs are invalid
int LWWalletTransactionIsValid(LWWallet *wallet, const LWTransaction *tx);

// true if transaction cannot be immediately spent (i.e. if it or an input tx can be replaced-by-fee)
int LWWalletTransactionIsPending(LWWallet *wallet, const LWTransaction *tx);

// true if tx is considered 0-conf safe (valid and not pending, timestamp is greater than 0, and no unverified inputs)
int LWWalletTransactionIsVerified(LWWallet *wallet, const LWTransaction *tx);

// set the block heights and timestamps for the given transactions
// use height TX_UNCONFIRMED and timestamp 0 to indicate a tx should remain marked as unverified (not 0-conf safe)
void LWWalletUpdateTransactions(LWWallet *wallet, const UInt256 txHashes[], size_t txCount, uint32_t blockHeight,
                                uint32_t timestamp);
    
// marks all transactions confirmed after blockHeight as unconfirmed (useful for chain re-orgs)
void LWWalletSetTxUnconfirmedAfter(LWWallet *wallet, uint32_t blockHeight);

// returns the amount received by the wallet from the transaction (total outputs to change and/or receive addresses)
uint64_t LWWalletAmountReceivedFromTx(LWWallet *wallet, const LWTransaction *tx);

// returns the amount sent from the wallet by the trasaction (total wallet outputs consumed, change and fee included)
uint64_t LWWalletAmountSentByTx(LWWallet *wallet, const LWTransaction *tx);

// returns the fee for the given transaction if all its inputs are from wallet transactions, UINT64_MAX otherwise
uint64_t LWWalletFeeForTx(LWWallet *wallet, const LWTransaction *tx);

// historical wallet balance after the given transaction, or current balance if transaction is not registered in wallet
uint64_t LWWalletBalanceAfterTx(LWWallet *wallet, const LWTransaction *tx);

// fee that will be added for a transaction of the given size in bytes
uint64_t LWWalletFeeForTxSize(LWWallet *wallet, size_t size);

// fee that will be added for a transaction of the given amount
uint64_t LWWalletFeeForTxAmount(LWWallet *wallet, uint64_t amount);

// outputs below this amount are uneconomical due to fees (TX_MIN_OUTPUT_AMOUNT is the absolute minimum output amount)
uint64_t LWWalletMinOutputAmount(LWWallet *wallet);

// maximum amount that can be sent from the wallet to a single address after fees
uint64_t LWWalletMaxOutputAmount(LWWallet *wallet);

// frees memory allocated for wallet, and calls LWTransactionFree() for all registered transactions
void LWWalletFree(LWWallet *wallet);

// returns the given amount (in satoshis) in local currency units (i.e. pennies, pence)
// price is local currency units per bitcoin
int64_t LWLocalAmount(int64_t amount, double price);

// returns the given local currency amount in satoshis
// price is local currency units (i.e. pennies, pence) per bitcoin
int64_t LWBitcoinAmount(int64_t localAmount, double price);

#ifdef __cplusplus
}
#endif

#endif // LWWallet_h
